[package]
name = "vm2-cep18"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
casper-contract-sdk = { path = "../../../sdk" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
serde_json = "1"
casper-contract-sdk = { path = "../../../sdk", features = ["cli"] }

[dev-dependencies]
casper-contract-sdk-codegen = { path = "../../../sdk_codegen" }

[build-dependencies]
casper-contract-sdk-codegen = { path = "../../../sdk_codegen" }
