[package]
name = "schema-inject"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
casper-macros = { path = "../../smart_contracts/macros" }
casper-sdk = { path = "../../smart_contracts/sdk" }