[package]
name = "vm2-harness"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
casper-executor-wasm-common = { path = "../../../../executor/wasm-common" }
casper-macros = { path = "../../../macros" }
casper-sdk = { path = "../../../sdk" }
impls = "1"
thiserror = "2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
serde_json = "1"
