[package]
name = "increment-counter"
version = "1.0.0"
authors = ["Maciej Zielinski", "Michał Papierski <michal@casper.network>"]
edition = "2021"

[[bin]]
name = "increment_counter"
path = "src/main.rs"
bench = false
doctest = false
test = false

[dependencies]
casper-contract = { path = "../../../contract" }
casper-types = { path = "../../../../types" }
