---
name: lints
# runs steps that are require nightly rust based on ./smart_contracts/rust-toolchain.toml
permissions:
  contents: read

on:
  push:
    branches:
      - dev
      - trying
      - staging
      - 'release-**'
      - 'feat-**'
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - dev
      - 'release-**'
      - 'feat-**'
    paths-ignore:
      - '**.md'

jobs:
  lints:
    name: lints
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: setup-nightly-rs
        run: |
          make setup-nightly-rs
          apt install wabt

      - uses: Swatinem/rust-cache@v2

      - name: check-format
        run: make check-format

      - name: doc
        run: make doc

      - name: lint
        run: make lint

