---
name: casper-node
permissions:
  contents: read

on:
  push:
    branches:
      - dev
      - trying
      - staging
      - 'release-**'
      - 'feat-**'
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - dev
      - 'release-**'
      - 'feat-**'
    paths-ignore:
      - '**.md'

jobs:
  lints:
    name: tests
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: Swatinem/rust-cache@v2

      - name: setup
        run: make setup

      - name: fmt
        run: make check-format

      - name: clippy
        run: make lint

      - name: doc
        run: make doc

      - name: audit
        run: make audit

      - name: check-std-features
        run: make check-std-features

      - name: check-testing-features
        run: make check-testing-features

      - name: test
        run: make test CARGO_FLAGS=--release

      - name: test-contracts
        run: make test-contracts CARGO_FLAGS=--release
