---
name: lints
permissions:
  contents: read

on:
  push:
    branches:
      - dev
      - trying
      - staging
      - 'release-**'
      - 'feat-**'
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - dev
      - 'release-**'
      - 'feat-**'
    paths-ignore:
      - '**.md'

jobs:
  lints:
    name: lints
    runs-on: ubuntu-latest
    container:
      image: rust:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4 #tag v2.4.0
        with:
          persist-credentials: false

      - uses: Swatinem/rust-cache@v2

      - name: setup
        run: make setup

      - name: fmt
        run: make check-format

      - name: clippy
        run: make lint

      - name: doc
        run: make doc

      - name: audit
        run: make audit
